server:
  port: 8189
  servlet:
    context-path: /security
spring:
  main:
    banner-mode: off
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: kObOx_326
#  thymeleaf:
#    enabled: true
#    check-template-location: true
